parameters:
    twig.extension.readable_html_enum_value.class: Multiservices\ArxisBundle\Twig\Extension\ReadableHtmlEnumValueExtension
services:
    twig.extension.readable_html_enum_value:
      class: %twig.extension.readable_html_enum_value.class%
      arguments: [%doctrine.dbal.connection_factory.types%]
      tags:
          - { name: twig.extension }
    twig.extension.multiservices.arxis:
      class: Multiservices\ArxisBundle\Twig\Extension\ArxisExtension
      public: false
      tags:
          - { name: twig.extension }
      arguments: ["@twig.loader"]    
    twig.extension.url64:
      class: Multiservices\ArxisBundle\Twig\Extension\Base64Extension
      tags:
          - { name: twig.extension }      
    multiservices.arxis.listener:
      class: Multiservices\ArxisBundle\EventListener\ControllerListener
      tags:
          - {name: kernel.event_listener,event: kernel.controller,method: onKernelController}
      arguments: ["@twig.extension.multiservices.arxis"]
    multiservices.arxis.form.type.users:
        class: Multiservices\ArxisBundle\Form\Type\UsersType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: users }  
      
  